### ISSUE TITLE
MantisBT 2.1.0 icons

### ISSUE THREAD

**Issue by achoscz** [mantisbt-plugins/BBCodePlus#18] opened 2017-03-02 16:01 UTC
Hi,
i dont see icons :/
i test uninstall all plugins and dont works :/
windows 10 FF, IE, Chrome same problem 
Some ideas?
Thanks![snag-0000](https://cloud.githubusercontent.com/assets/26145040/23515135/9613c4fe-ff69-11e6-8579-d39ba262dc89.png)

**Comment by Kirill** [comment] 2017-03-13 08:26
Check files on server and access to it 
/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/bold.png

**Comment by achoscz** [comment] 2017-03-13 09:01
I see this. Is it OK? ![snag-0000](https://cloud.githubusercontent.com/assets/26145040/23847720/feb0dc78-07d3-11e7-8d28-d820720065f3.png)

**Comment by Kirill** [comment] 2017-03-13 09:03
not. you must see this
![2017-03-13 11_03_24](https://cloud.githubusercontent.com/assets/302940/23847794/baec9ca8-07dc-11e7-867a-63c29c869f3a.png)

**Comment by achoscz** [comment] 2017-03-13 09:05
All folders and files have the attributes 777. Some bad?

**Comment by Kirill** [comment] 2017-03-13 09:06
What apache or nginx log told?

**Comment by achoscz** [comment] 2017-03-13 09:35
This is the right address? `https://******.cz/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/bold.png` If I change bold.png on FTP another picture, so I still loading the original one

**Comment by achoscz** [comment] 2017-03-13 09:44
others image with tranparent backround on site is ok

**Comment by Kirill** [comment] 2017-03-13 09:53
other not plugin?
what's in apache log?

**Comment by achoscz** [comment] 2017-03-13 10:30
plugins/BBCodePlus/files/markitup/sets/default/images/bold.png  is ok, but plugin_file.php?file=... is problem.
for log moment

**Comment by Kirill** [comment] 2017-03-13 10:34
@achoscz , it's mean that your site can't render image by plugin. For example, you have nginx <-> apache <-> php. For image you have settings in nginx, but nginx don't know about php and can't put image from plugin. Check it and if nginx has this settings, try comment it and see result.

**Comment by achoscz** [comment] 2017-03-13 11:35
Apache Log

Error.txt
`[Mon Mar 13 06:25:02.633717 2017] [ssl:warn] [pid 731] AH01909: prg-srv-web:443:0 server certificate does NOT include an ID which matches the server name
[Mon Mar 13 06:25:02.634442 2017] [mpm_prefork:notice] [pid 731] AH00163: Apache/2.4.10 (Debian) mpm-itk/2.4.7-02 OpenSSL/1.0.1k configured -- resuming normal operations
[Mon Mar 13 06:25:02.634457 2017] [core:notice] [pid 731] AH00094: Command line: '/usr/sbin/apache2'`
or
access.log
`[13/Mar/2017:11:29:16 +0100] "GET /plugins/BBCodePlus/files/markitup/sets/default/images/bold.png HTTP/1.1" 200 784 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"`

**Comment by Kirill** [comment] 2017-03-13 11:49
This what I mean... Apache don't write log for access plugin_file.php?file=..., because all request ended to image file worked by nginx.

**Comment by achoscz** [comment] 2017-03-13 12:10
How settings Nginx? We do not use Nginx

**Comment by Kirill** [comment] 2017-03-13 13:13
Can you send me domain name of your installation?

**Comment by bkraul** [comment] 2017-03-13 13:50
@achoscz What does the Chrome Web Developer Tools console say? 

You can access it by going to the menu, and select More Tools -> Developer Tools, or by pressing Ctrl + Shift + I. It looks like this.

![image](https://cloud.githubusercontent.com/assets/14616851/23857117/093d60e4-07ca-11e7-8541-d60299a8c0f0.png)

Usually if there are any items blocked you will see them in red. This could be an issue of CSP restrictions.

Please refer to [this issue](https://github.com/mantisbt-plugins/BBCodePlus/issues/3).

**Comment by achoscz** [comment] 2017-03-14 07:26
`https://bt.mediclinic.cz`

**Comment by achoscz** [comment] 2017-03-14 07:38
@bkraul FF, IE and Edge same problem :/
![snag-0000](https://cloud.githubusercontent.com/assets/26145040/23890255/4935a3e2-0891-11e7-89a5-d6118ea23bba.png)

**Comment by Kirill** [comment] 2017-03-14 07:41
@achoscz , sorry. I can't access to this site. Try open Console and Refresh page

**Comment by achoscz** [comment] 2017-03-14 07:45
@Kirill refresh and same window

**Comment by achoscz** [comment] 2017-03-14 07:46
@Kirill i can run teamviewer

**Comment by Kirill** [comment] 2017-03-14 08:02
@achoscz can you contact with me on skype krasnov.kirill ?

**Comment by achoscz** [comment] 2017-03-14 08:04
@Kirill added (premek.parma)

**Comment by bkraul** [comment] 2017-03-17 13:04
@achoscz Your screenshot shows the 'Sources' tab of the developer tools. I am interested on the 'Console' tab. I want to see what errors you are getting that are preventing the images to load:

![image](https://cloud.githubusercontent.com/assets/14616851/24044206/55a166ee-0ae8-11e7-93e6-6855a7bec655.png)

**Comment by achoscz** [comment] 2017-03-17 13:12
@bkraul 
![snag-0001](https://cloud.githubusercontent.com/assets/26145040/24044470/b00d3a58-0b1b-11e7-9b55-e44da0e9a5c0.png)

**Comment by bkraul** [comment] 2017-03-17 13:20
Those JS timeouts don't look good. I tried to access your site but apparently it is not available to the outside world?

**Comment by achoscz** [comment] 2017-03-17 13:22
@bkraul only allowed in my country :/

**Comment by bkraul** [comment] 2017-03-17 13:29
Czech Republic? let me see if I can access it through a proxy. I'll let you know what I find. While we are at it, is there any way you can create me a reporter user account to test? Shoot me the access data at bkraul@yahoo.com .

**Comment by bkraul** [comment] 2017-03-17 13:33
I can see your site. Now I just need the account to access.

**Comment by achoscz** [comment] 2017-03-17 13:42
@bkraul test pass: test123

**Comment by bkraul** [comment] 2017-03-17 14:08
@achoscz I logged in and cannot see the images just like you, so I tried accessing a single image by using the direct URL of one of the images, such as this:

```https://bt.mediclinic.cz/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/bold.png```

The error I get was this:

```The image "https://bt.mediclinic.cz/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/bold.png" cannot be displayed because it contains errors.```

So, I downloaded the file in order to check if it is outputting as a valid PNG, and what I found out is that it is not. Take a look at the first bytes of a valid PNG file:

```89 50 4E 47 0D``` which translates to ASCII as ```‰PNG```

But your installation is outputting the image as:

```EF BB BF 89 50 4E 47 0D``` which translates to ASCII as ```ï»¿‰PNG.```

This means, that somewhere in your installation, there is output being done BEFORE the image headers are written by *plugin_file.php*. It could be as simple as an incorrectly encoded php file, or maybe if you have updated */config/config.inc.php* and added an incorrect space or character. There is really no way to tell. I suppose you could send me your whole web directory zipped (I don't need the database as I can create a new one), so that I can pin point where the offending data chunk is.

Have you tried disabling any other non-core plugins and see if that helps?

**Comment by bkraul** [comment] 2017-03-17 14:16
More info. I can confirm that you have a script encoding issue. The offending bytes, ```EF BB BF``` are what is called a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark), or BOM for short. Your php files should be encoded as UTF-8 **without** BOM. This is what your problem is. You might want to try re-downloading **plugin_file.php** from the original install and replacing your existing one. However, if that works, there is a chance you have more files like that, and you probably need to refresh your whole installation.

**Comment by bkraul** [comment] 2017-03-17 15:59
@achoscz Please do not forget to report back once your issue is resolved, so as to close this issue.

**Comment by achoscz** [comment] 2017-03-20 09:41
@bkraul ok
i test:
- UTF-8 without BOM
- Replace plugin_file.php
still same problem :(
here is zipped directory
`https://drive.google.com/open?id=0B1sUrhFsgUQcUWNVOTM4eVgwWTg`

**Comment by bkraul** [comment] 2017-03-20 16:25
This is odd. I set up your files on a host to test, and this is the result I get using your same files. I know it is an encoding problem, I just wish I could troubleshoot your actual set up, as I seem unable to replicate your issue.
![image](https://cloud.githubusercontent.com/assets/14616851/24109849/e5ad4c02-0d5f-11e7-81c0-d98f7b965a0c.png)

**Comment by atrol** [comment] 2017-03-20 17:08
@bkraul I assume you will able to reproduce the issue if you change language to Czech.
The file lang/strings_czech.txt has been changed (of course you should never change the file) and is stored with BOM.

**Comment by bkraul** [comment] 2017-03-20 18:14
Thanks @atrol I am not sure. I tried it with czech and it still showed images. My guess is that the database encoding also has something to do with it (I do not have his database). In any case, files such as the one you mention should be without BOM. I use utf8_general_ci as my mysql db encoding. @achoscz, what is the encoding of your db?

**Comment by achoscz** [comment] 2017-03-21 08:38
@bkraul utf8 general ci

**Comment by bkraul** [comment] 2017-04-20 13:57
Closed as an environment issue unrelated to BBCodePlus.

**Closed as completed by bkraul** 2017-04-20 13:57 UTC
