### ISSUE TITLE
Cannot get the toolbar to work (IIS8.5 + PHP Environment)

### ISSUE THREAD

**Issue by sachintha81** [mantisbt-plugins/BBCodePlus#34] opened 2019-03-12 16:22 UTC
I installed BBCodePlus plug-in in my mantis installation, and it works on text areas just fine. I can manually do [ b]some text[ /b] etc and it will show me bold/italic etc.

However I cannot figure out how to get the toolbar to work. But according to the plugin Wiki, it's supposed to show you a toolbar.

This is what my config options look like:

![bbcode](https://user-images.githubusercontent.com/8787573/54217199-65863700-44a8-11e9-9f64-9edd1fcf4ed9.PNG)

Is there a set of steps/installation guide? Otherwise, is there anything else I need to do to get it working.

**Here's my mantis and my system information.**
OS: Windows Server 2012 R2 (Version 6.2, Build 9200)
IIS Version: 8.5.9600.16384
PHP Version: 7.2.7 (verified that it's working)
Mantis Version: MantisBT 2.19.0
Browser: Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by bkraul** [comment] 2019-03-12 16:30
Check #31, this might be your issue as well.

**Comment by sachintha81** [comment] 2019-03-12 16:37
Thanks for the reply!

On that note, looks like I haven't installed Markitup. But how do I do that - I didn't find anything here on that? Do I copy it into the same folder as mantis?

Markitup has an installation guide, but I don't know how it would work with Mantis/BBCode Plus?

![mark](https://user-images.githubusercontent.com/8787573/54218284-82bc0500-44aa-11e9-85d1-e974c0dc3175.PNG)


EDIT:
I checked and have no newline characters in any of my config files.

**Comment by bkraul** [comment] 2019-03-12 16:40
No man, you don't need to install MarkItUp, it is all included in the plugin. If you are not seeing the tool bar it is likely that the problem is what I pointed out.

**Comment by sachintha81** [comment] 2019-03-12 16:41
I see. So I did check the config files and there are no new lines, and I also did not do any security changes. Is there a list of files I should check?

**Comment by bkraul** [comment] 2019-03-12 16:43
Can you send a screenshot of a text area (like new issue or comment) to see what it looks like?

**Comment by sachintha81** [comment] 2019-03-12 16:47
This is how it looks like in the 'Create Issue' section. 'Problem Description' is the default 'Summary' filed, I just changed the caption. There's a bunch of additional custom textareas I've created as well and they too look the same.

![issuenew](https://user-images.githubusercontent.com/8787573/54218997-d418c400-44ab-11e9-90d5-c3b1f8c5e567.PNG)

And following is the 'Add New Note' section.

![issuenote](https://user-images.githubusercontent.com/8787573/54219009-dc70ff00-44ab-11e9-8f0c-7b4e53065979.PNG)

**Comment by bkraul** [comment] 2019-03-12 16:50
One more thing, if in Chrome or Firefox, press F12 and display the developer toolbar. Then make sure you are on the Networking tab and refresh the page....you should see a list pop up:

![image](https://user-images.githubusercontent.com/14616851/54219201-0b43a100-44bd-11e9-9b9b-95198e1288a2.png)

I am interesting on seeing the errors.

**Comment by sachintha81** [comment] 2019-03-12 16:51
Also, I tried some BBCode formatting, the basic ones like bold, italic work but not color.

![red](https://user-images.githubusercontent.com/8787573/54219285-78026f80-44ac-11e9-9e3c-ea026eb3f275.PNG)

**Comment by sachintha81** [comment] 2019-03-12 16:54
Here's the list you asked for:

![nwerror](https://user-images.githubusercontent.com/8787573/54219491-d9c2d980-44ac-11e9-8fae-8d39a49df66a.PNG)

**Comment by bkraul** [comment] 2019-03-12 16:59
Hmmm, the status codes seem fine. Let me do some further digging. I assume you are using the latest master version?

**Comment by sachintha81** [comment] 2019-03-12 17:10
Thank you! Please let me know if you find anything.

Yes I downloaded as a zip the latest version from here. Version: 1.x-1.1.15.zip


Also, I tested most of the BBCodes, results below. Some work but some like [img], text color and highlight color, don't seem to work either.

![bbtest](https://user-images.githubusercontent.com/8787573/54220624-1099ef00-44af-11e9-9913-7b3f92a8d416.PNG)

**Comment by bkraul** [comment] 2019-03-12 17:14
Wait, but your screenshots show you have mantis 2.x...? If so, you need to install the version of BBCodePlus for that version of mantis, from the 2.0.x branch:

https://github.com/mantisbt-plugins/BBCodePlus/tree/master-2.0.x

**Comment by sachintha81** [comment] 2019-03-12 17:18
Sorry, that was the Markitup version I typed above, by mistake.

I have the correct BBCode version - 2.0.

**Comment by sachintha81** [comment] 2019-03-12 17:26
And, do I need to install anything else like JQuery/Json etc? I'm working on a pretty bare bones machine that I install things as I go.

**Comment by bkraul** [comment] 2019-03-12 17:48
Not that I know of. Mantis provides the jQuery stuff. My challenge here will be to replicate your IIS environment, as I (and probably mostly everyone) runs on apache/php. I am curious if that has anything to do with your issue.

**Comment by sachintha81** [comment] 2019-03-12 17:56
OK so this almost certainly to do with my system.

I have a second mantis installation on a different machine, and the plugin works there. It's on Windows 7, and here's a comparison of the two systems. I'm not sure how to narrow down the problem now though.

Win 7 (plugin WORKS)
--------------------------------
Windows 7 Professional, SP1 (64 bit)
MantisBT: 2.19.0
PHP: 2.7.2
IIS Version: 7.5.7600.16385


Windows Server 2012 R2 (plugin does NOT work)
------------------------------------------------------
Windows Server 2012 R2 Standard (64 bit)
MantisBT: 2.19.0
PHP: 2.7.2
IIS Version: 8.5.9600.16384

**Comment by bkraul** [comment] 2019-03-12 18:05
On your PHP, I think you may be meaning 7.2.2...

Hence the kicker. You see, nowadays I run all of my web stuff on docker (on linux). You can also run IIS on docker but you have to have a Windows box. And even then it will likely not be a true IIS scenario like what you have on the Win 2012 Server.

**Comment by bkraul** [comment] 2019-03-12 18:08
Can you go here for a min? Enter whatever name you want.

https://rocketchat.belmankraul.com/livechat

**Comment by sachintha81** [comment] 2019-03-12 18:12
No the PHP version is 7.2.7, please see:

![phpver](https://user-images.githubusercontent.com/8787573/54224879-aa659a00-44b7-11e9-8e38-307a18118b87.PNG)

**Comment by bkraul** [comment] 2019-03-13 14:38
OK. Per our conversation, I set up my clean environment in order to replicate. I did find some issues with the implementation that have to do with CSP (Content Security Policy). I have found a way to correct this, and I am currently cleaning up for a PR. Hopefully after this, it will either work, or we will have a better idea of what is going on.

**Comment by bkraul** [comment] 2019-03-13 16:06
@sachintha81 Please check the latest [master-2.0.x](https://github.com/mantisbt-plugins/BBCodePlus/tree/master-2.0.x) code. I am hoping this will solve your issue (along with you trying a new environment).

**Comment by sachintha81** [comment] 2019-03-13 18:54
Hey, thanks for the update! Unfortunately though, the problem still persists for me. I installed a fresh copy of Mantis and then this new plugin version, but I still don't get the toolbar.

![Capture](https://user-images.githubusercontent.com/8787573/54306581-e582ce80-4586-11e9-936d-117c748cd7de.PNG)

**Comment by bkraul** [comment] 2019-03-13 21:48
Just for kicks...have you tried clearing any cache on the browser you are trying to access your mantis installation from? Like clearing all the storage for the site, or even doing a "Forget this site"?

**Comment by sachintha81** [comment] 2019-03-13 22:14
Yeah did a full clean even including passwords. No luck.

**Comment by bkraul** [comment] 2019-03-13 22:20
I think I'm just going to bite the bullet, and set me up a new VM with Server 2012 R2, IIS, and PHP. That will be the only way I will be able to look at this and trying to find an issue. Are you running mantis in a subdirectory? Or in the root of your default website ( C:\inetpub\wwwroot )?

**Comment by bkraul** [comment] 2019-03-14 02:04
OK I have the installation ready for when you answer my question about root. I did find out that there is now a really neat way to install and maintain php versions on IIS 7+ (Server 2012 comes with 8), called the [PHP Manager](https://www.iis.net/downloads/community/2018/05/php-manager-150-for-iis-10). I am not sure how you are installing your version of PHP (I followed [this guide](https://www.howtogeek.com/50432/how-to-install-php-on-iis-7-for-windows-server-2008/) for IIS7 but most of it also works for IIS8), but I could not find PHP version 7.2.7. The official windows version available from [php.net](https://windows.php.net/download/) is 7.2.16, and is very easily installable with the PHP Manager module.

I will likely be able to help you with this tomorrow, given that I do have the IIS mantis 2.19 environment ready to install:

![image](https://user-images.githubusercontent.com/14616851/54326172-9911b000-45d3-11e9-98d2-6c61edf26516.png)

Let me know.

**Comment by bkraul** [comment] 2019-03-14 16:05
I was able to replicate the behavior of your issue on my Windows Server 2012 box. It seems it is a path issue when it comes to accessing plugin files, in this case the BBCodePlus intialization file. I am doing more digging. Hopefully will have something soon.

**Comment by bkraul** [comment] 2019-03-14 16:13
I believe I have found the solution to your problem. The issue is that the plugin system is trying to get file information on any plugin files that are being loaded. I found this as an error on the php eror log:
```
[14-Mar-2019 11:05:42 America/Chicago] Class 'finfo' not found
C:\inetpub\wwwroot\mantisbt\core\file_api.php
```
Doing some googling on this, came to find out that that the class `finfo` exists in the fileinfo PHP extension, which is not enabled by default on a new PHP installation. So, your solution will be to make sure that extension is enabled on the `php.ini` file by making sure this line exists:
```
extension=php_fileinfo.dll
```
and then restart IIS.

Again, this is a breeze if you are using the PHP Manager extension for IIS. Let me know and I can guide you through setting that up.

If this fixes your issue, please let me know so I can close it as resolved.

**Comment by sachintha81** [comment] 2019-03-14 16:14
Sorry for the late reply. Here are answers to your questions:

1. I initially had mantis in a subdirectory (wwwroot/mantis), and later I also tried directly under wwwroot. It did not work in either case.
2. I too have PHP manager installed.
3. I downloaded PHP from Web Platform Installer. You can install it from the following link. You can get PHP 7.2.7 from there.
https://www.microsoft.com/web/downloads/platform.aspx

**Comment by bkraul** [comment] 2019-03-14 16:16
I just created me a `C:\php\7.2.16` folder and dropped the latest php.net Windows binaries and then enabled it on PHP manager. I guess either way works.

**Comment by sachintha81** [comment] 2019-03-14 16:16
> Doing some googling on this, came to find out that that the class `finfo` exists in the fileinfo PHP extension, which is not enabled by default on a new PHP installation. So, your solution will be to make sure that extension is enabled on the `php.ini` file by making sure this line exists:
> 
> ```
> extension=php_fileinfo.dll
> ```

Enabling that extension is required to get PHP file uploads to work, so I already have that set up.

**Comment by bkraul** [comment] 2019-03-14 16:17
I see. Well, on that front, does the php log provide any other error information when you try to log the "Report Issue" page?

**Comment by bkraul** [comment] 2019-03-14 16:18
I also had to make sure all my composer requires were up to date. Actually, initially I didn't have the vendor folder so I had to do that first. I am sure you did that, because otherwise mantis would not run.

**Comment by sachintha81** [comment] 2019-03-14 16:19
Actually, I haven't been able to get file uploads to work on that machine either. I'm still trying to get a fresh copy of Windows installed there.

But other than that I don't get any errors when I create a new issue.

**Comment by bkraul** [comment] 2019-03-14 16:20
These are the extensions I have enabled:
![image](https://user-images.githubusercontent.com/14616851/54373321-090f4d00-464b-11e9-9fbe-9c21f155b88d.png)

And here is the plugin functioning.
![image](https://user-images.githubusercontent.com/14616851/54373370-2217fe00-464b-11e9-8400-3f7884f5a7d5.png)

**Comment by sachintha81** [comment] 2019-03-14 16:20
Let me know if you want to talk in the chat. It's not active.

**Comment by sachintha81** [comment] 2019-03-14 16:21
My enabled extensions.

![ext](https://user-images.githubusercontent.com/8787573/54373492-95654400-463a-11e9-8f22-ad3a51ad8f38.PNG)

**Comment by bkraul** [comment] 2019-03-14 16:24
Huh...I seem to have temporarily lost internet at home (where my servers are running). I'll give it a few minutes for it to come back. I generally do have a very dependable link, but we have been having some rough weather lately.

**Comment by sachintha81** [comment] 2019-03-14 16:25
OK no worries, I'll be here all day.

I wonder if this is a problem with IIS8 though; you're testing on IIS 7 right?

**Comment by bkraul** [comment] 2019-03-14 16:26
No man, my setup is as close as I could get to yours, Windows Server 2012 R2 (IIS 8.5):
![image](https://user-images.githubusercontent.com/14616851/54373884-05c89100-464c-11e9-9b55-be92f546f4c5.png)

**Comment by sachintha81** [comment] 2019-03-14 16:28
Then I'll try with your version of PHP, that's the only difference atm?

**Comment by bkraul** [comment] 2019-03-14 16:29
Yeah. Like I said, I just download the 7.2.16 NTS version (after making sure I have the latest VC15 runtimes), put the files inside folder `C:\php\7.2.16`, and add the version to the PHP manager.

**Comment by bkraul** [comment] 2019-03-14 16:42
Livechat is back. 🎧

**Comment by sachintha81** [comment] 2019-03-14 16:42
Still no luck. 
Installed v7.2.16 (see PHPInfo below), and then cleared browser cache, restarted IIS, and still the same:

![phpinfo](https://user-images.githubusercontent.com/8787573/54375035-8338d500-463d-11e9-83ed-df7fdd9e6a32.PNG)

![issue](https://user-images.githubusercontent.com/8787573/54375044-86cc5c00-463d-11e9-9dde-a5dc4d85872b.PNG)

**Comment by sachintha81** [comment] 2019-03-14 16:49
Chat still says Bad Gateway.

**Comment by bkraul** [comment] 2019-03-14 16:49
That's wild. It is the exact same environment. And as you said, you checked the php error log file when you load the "Report New Issue" page and no errors are logged?

**Comment by sachintha81** [comment] 2019-03-14 16:52
Yes, no errors. I think this system is unsalvageable at this point. Like I mentioned even file uploads aren't working although everything is set the way it should. I think I'll let you know once I attempt on the new system, it should be ready for me soon.

**Comment by bkraul** [comment] 2019-03-14 17:02
Yeah, I'd try that and see. It definitely seems something is jacked up with the current setup. At least we do know that it is not a Server 2012 issue across the board. Currently trying to restore livechat functionality. Will let know know when it is back on. Sorry for that. Outages do do a number sometimes.

**Comment by bkraul** [comment] 2019-03-14 17:37
Now Livechat is back for sure, hehe 🎧.

**Comment by sachintha81** [comment] 2019-03-15 19:25
OK, finally it's working!

I installed a fresh copy of Windows Server 2012 R2 on a virtual machine and started from scratch. Here's the configuration.

OS: Windows Server 2012 R2 Standard
IIS Version: 8.5.9600.16384
PHP Version: 7.2.14
MySQL: 8.0.15
MantisBT: 2.19.0
BBCode+ 2.0.18

All formatting except for [img] works.

**Comment by sachintha81** [comment] 2019-03-15 19:26
As you can see the [img] tag doesn't work but honestly I can live with that.
Thanks for all your work on this!

![bb1](https://user-images.githubusercontent.com/8787573/54457000-6ffd3680-471d-11e9-913d-308daaf264bb.PNG)

![bb2](https://user-images.githubusercontent.com/8787573/54457005-72f82700-471d-11e9-9bd5-f9694ef0d4e7.PNG)

**Closed as completed** 2019-03-15 19:37 UTC
Labels: status: solved by op

**Comment by bkraul** [comment] 2019-03-18 19:07
@sachintha81: A new version of BBCodePlus has been released with a brand new parser system that should address your issue with images not being displayed, along with many other enhancements and fixes. This version is for MantisBT 2.x.

You are welcome to download it [here](https://github.com/mantisbt-plugins/BBCodePlus/releases/tag/v2.1.0).

**Comment by sachintha81** [comment] 2019-03-18 19:10
Works great, including the [img] tag. Thanks!
